#+TITLE: Unit 3: Mass and Force Concepts
#+AUTHOR: Fethi Okyar
#+DATE: 2025-04-13
#+SUBTITLE: Readings from Stuart and Gonzales, Chapter 3
#+STARTUP: overview
#+REVEAL_THEME: simple
#+REVEAL_INIT_OPTIONS: slideNumber:"c/t", width:1920, height:1080
#+REVEAL_TITLE_SLIDE: <h2>%t</h2> <h3>%s</h3> <h4>%d</h4>
#+OPTIONS: timestamp:nil toc:1 num:nil
#+REVEAL_EXTRA_CSS: ../style.css
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js


* ($\S 3.1$) Continuum Bodies (Session 9)
#+ATTR_HTML: :width 600px
[[../images/Continuum_body.svg]]
#+ATTR_REVEAL: :frag (appear appear appear ...)
- What is the notion of a /[[https://en.wikipedia.org/wiki/Continuum_mechanics][continuum]]/? (ask chat AI)
- In this context define *density* of a material, $\rho$ (units in mass/volume)
- We identify the /placement of a *material body*/ as an open subset $B$ of Euclidean Space $\mathbb{E}^3$
- The placement of a body may change in time, i.e. $B=B(t)$, under the effect of external factors.
- Study of the relationship between the change in placement and external factors, is called /continuum mechanics/.

** ($\S 3.2$) Volume and Mass
#+ATTR_HTML: :width 300px
[[../images/Continuum_body.svg]]
#+ATTR_REVEAL: :frag (appear appear appear ...)
- The *mass* of the body is distributed continuously throughout its *volume*.
- The volume of an arbitrary open subset $\Omega$ of $B$ is $$\mathrm{vol}[\Omega] = \int_\Omega dV.$$ where $dV$ denotes an infinitesimal volume element at $\boldsymbol{x}\in\Omega$.
- Let there be a *mass density* field per unit volume $\rho:B\to\mathbb{R}$ such that $$\mathrm{mass}[\Omega] = \int_\Omega \rho(\boldsymbol{x})dV.$$

#+REVEAL: split
*** ($\S 3.2.2$) Centers of Volume and Mass
#+ATTR_HTML: :width 300px
[[../images/Continuum_body.svg]]
#+ATTR_REVEAL: :frag (appear)
- By the center of volume of an open subset $\Omega$ of $B$ we mean the point $$\boldsymbol{x}_\mathrm{cov} = \frac{1}{\mathrm{vol}[\Omega]} \int_\Omega \boldsymbol{x} dV.$$
- By the center of mass of an open subset $\Omega$ of $B$ we mean the point $$\boldsymbol{x}_\mathrm{com} = \frac{1}{\mathrm{mass}[\Omega]} \int_\Omega \boldsymbol{x} \rho(\boldsymbol{x}) dV.$$
  
** ($\S 3.3$) Force
#+ATTR_REVEAL: :frag (appear)
- The abstract notion describing the physical effect of attraction/repulsion.
- Units of force: Newton (SI), dyne (SI), pounds (US), etc.
*** ($\S 3.3.1$) Body Force
#+ATTR_REVEAL: :frag (appear)
- This term refers, in general, to any force field, $\boldsymbol{b}(\boldsymbol{x})$, that does not arise from physical contact (between bodies).
- Example: gravity, $g$ (has units of m/s$^2$)
- It is usually measured in terms of the force field per unit mass (i.e. force/mass)
- Let $\Omega$ be an arbitrary subset of $B$. Then the resultant force on $\Omega$ due to a body force field is defined as $$\boldsymbol{r}_b[\Omega] = \int_\Omega \rho(\boldsymbol{x}) \boldsymbol{b}(\boldsymbol{x}) dV,$$
- and the resultant torque, about a point $\boldsymbol{z}$, becomes  $$\boldsymbol{\tau}_b[\Omega] = \int_\Omega (\boldsymbol{x} - \boldsymbol{z}) \times \rho(\boldsymbol{x}) \boldsymbol{b}(\boldsymbol{x}) dV.$$
  
** Questions for next session
Ask AI:
- How can the stress tensor be introduced in a simple but mathematically concise manner?
  
** Deliverables
Students should be able to:
- [ ] use density to find continuum mass and center of mass

  
